### ISSUE TITLE
🚀 FEAT: MongoDB Crud App

### ISSUE THREAD

**Issue by muriusbane** [mayajs/sample#14]
## 📝 Description
Create a crud app using MongoDB

## 📋 Todo:

- [x] Set-up mayajs and MongoDB
- [x] Add route to get all users
- [x] Add route to get user by ID
- [x] Add route to create user
- [x] Add route to update user by ID
- [x] Add route to delete user by ID

## 🔍 Additional Info
I submitted PR #13 for this issue
