### ISSUE TITLE
🚀 FEAT: TODO App sample projects

### ISSUE THREAD

**Issue by Mackignacio** [mayajs/sample#5]
## 📝 Description

We need to have a sample project that shows how MayaJS connect with various front-end technologies. See list below:
- Angular
- React
- Vue
- Svelte
- Flutter

## 📋 Todo:
- [x] Create Angular - #11
- [x] Create React - #6
- [x] Create Vue  - #12
- [x] Create Svelte  - #15
- [x] Create Flutter - #7
- [x] Create mayajs app
  - [x] Connect mayajs to a database i.e. MongoDB
  - [x] Create a model for a task
  - [x] Create a GET request endpoint to fetch all todo list
  - [x] Create a GET request endpoint to fetch todo by id
  - [x] Create a POST request endpoint to add a todo task
  - [x] Create a PUT request endpoint to update a todo task
  - [x] Create a DELETE request endpoint to delte a todo task
- [x] Connect angular to mayajs
- [x] Connect react to mayajs
- [x] Connect vue to mayajs
- [x] Connect svelte to mayajs
- [x] Connect flutter to mayajs

### Each todo app task
- Create a todo list page
- Create a page to view a specific todo task
- Create add button to add a todo task
- Create delete button to delete a todo task
- Create update button to update a todo task

### This is a sample UI for a TODO app
![image](https://user-images.githubusercontent.com/12345233/89004924-d811e400-d335-11ea-9178-c76f1d7da124.png)

### No todo item
![image](https://user-images.githubusercontent.com/12345233/89004860-b3b60780-d335-11ea-9ef5-5160b695e9d6.png)

**Comment by jacepm** [comment]
I have a PR #7 for flutter todo app. Kindly check it. Thanks.

**Comment by Mackignacio** [comment]
> I have a PR #7 for flutter todo app. Kindly check it. Thanks.

Thank you I will add this on the list.

**Comment by ryama141** [comment]
Please check my PR #10 for angular todo app. Thanks 😄 👍

**Comment by jacepm** [comment]
Kindly check PR #12 for vue todo app. Thanks 👍

**Comment by Mackignacio** [comment]
> Please check my PR #11 for angular todo app. Thanks 😄 👍
> Kindly check PR #12 for vue todo app. Thanks 👍

Adding this two PR. Thank you. 👍 👍 💯

**Comment by Mackignacio** [comment]
Svelte todo app PR #15
