### ISSUE TITLE
🚀 FEAT: Simple Login Api

### ISSUE THREAD

**Issue by Mackignacio** [mayajs/sample#9]
## 📝 Description

Create a mayajs project that demonstrate how to create a simple login api.

## 📋 Todo:

- [x] Create a mayajs app
- [x] Create user controller
- [x] Create login end point
- [x] Add validation for login endpoint
- [x] Add error response when password is not correct
- [x] Add error response when username is not correct

**Comment by rhonumahon** [comment]
I have finished this sample login API in PR #16 👍 💯 😄
